// Purpose: Verify source alignment, parser contracts, advisory review and provenance failures.
import test from 'node:test';
import assert from 'node:assert/strict';
import { compare, parseMarkdown, parseText, review, toMarkdown } from '../src/index.mjs';
const diff = () => compare('# Retry\nMay retry.', '# Retry\nMust retry once.');
test('changed section retains exact source and line references', () => { const d = diff(); assert.equal(d.changes.length, 1); assert.equal(d.changes[0].kind, 'modified'); assert.equal(d.changes[0].before.startLine, 1); assert.match(d.changes[0].after.text, /Must retry once/); assert.notEqual(d.beforeFingerprint, d.afterFingerprint); });
test('unchanged and moved sections need no model judgment', () => { assert.equal(compare('# A\nhello\n# B\nworld', '# B\nworld\n# A\nhello').changes.length, 0); });
test('fenced code headings are not interpreted as sections', () => { const p = parseMarkdown('# A\n```md\n# fake\n```\n# B\nreal'); assert.equal(p.length, 2); assert.match(p[0].text, /# fake/); });
test('renamed sections are removed and added, duplicate headings stay distinct', () => { assert.deepEqual(compare('# A\nx', '# B\nx').changes.map(c => c.kind), ['removed', 'added']); assert.equal(parseMarkdown('# A\nx\n# A\ny').length, 2); });
test('custom parser rejects duplicate ids and supports plaintext', () => { assert.throws(() => compare('a', 'b', { parser: () => [parseText('a')[0], parseText('b')[0]] }), /duplicate/); assert.equal(compare('a', 'b', { parser: parseText }).changes[0].id, 'document'); });
test('low probability remains uncertain and all judgments advisory', async () => { const r = await review(diff(), { reviewer: async () => ({ category: 'weakened', probability: .4 }) }); assert.equal(r.changes[0].judgment.category, 'uncertain'); assert.equal(r.changes[0].requiresReview, true); assert.match(toMarkdown(r), /uncertain/); });
test('budget rejects before provider calls and tampering rejects before review', async () => { let calls = 0; const reviewer = async () => { calls++; return { category: 'editorial', probability: 1 }; }; await assert.rejects(review(diff(), { reviewer, maxChanges: 0 }), /budget/); const d = diff(); d.changes[0].before.text = 'tampered'; await assert.rejects(review(d, { reviewer }), /provenance/); assert.equal(calls, 0); });
test('plugin timeout, cancellation and invalid classifications propagate', async () => { await assert.rejects(review(diff(), { reviewer: () => new Promise(() => {}), timeoutMs: 5 }), /deadline/); await assert.rejects(review(diff(), { reviewer: async () => ({ category: 'made_up', probability: 1 }) }), /Invalid reviewer/); const controller = new AbortController(); controller.abort(new Error('cancelled')); await assert.rejects(review(diff(), { reviewer: async () => ({}), signal: controller.signal }), /cancelled/); });
